# [문제] 서울시 부동산 2024(2024.csv) — 기본 전처리 & 인덱싱/슬라이싱
> **주의:** 아래 문제는 반드시 제공된 문법 안에서만 풀이하세요.
- 사용 가능: `read_csv`, `to_csv`, `Series`, `DataFrame`, `head`, `shape`, `info`, `describe`, `value_counts`, `to_datetime`
- 인덱싱/슬라이싱: `[]`, `[['col1','col2']]`, `.loc`, `.iloc`, 슬라이싱(끝 포함/제외), 불리언 필터, `&`, `|`
- 결측치: `isnull().sum()`

## 0) 환경 세팅
- 파일 경로: `2024.csv` (인코딩: `cp949`)
- 열(예시): `자치구명`, `법정동명`, `지번구분`, `본번`, `부번`, `건물명`, `계약일`, `물건금액(만원)`, `건물면적(㎡)`, `토지면적(㎡)`, `층`, `권리구분`, `취소일`, `건축년도`, `건물용도`, `신고구분`, `신고한 개업공인중개사 시군구명`

In [1]:

import pandas as pd

path = "2024.csv"
df = pd.read_csv(path, encoding="cp949")
print("로드 완료!")

로드 완료!

C:\Users\j2h09\AppData\Local\Temp\ipykernel_27176\2657875834.py:4: DtypeWarning: Columns (7,8) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(path, encoding="cp949")

### 문제 1. 데이터 처음 5행을 확인하세요 (`head()`).

In [2]:
df.head()

,접수연도,자치구코드,자치구명,법정동코드,법정동명,지번구분,지번구분명,본번,부번,건물명,...,물건금액(만원),건물면적(㎡),토지면적(㎡),층,권리구분,취소일,건축년도,건물용도,신고구분,신고한 개업공인중개사 시군구명
0,2024,11380,은평구,10200,녹번동,1.0,대지,86.0,125.0,성원빌라(86-125),...,16400,53.07,25.0000,4.0,NaN,NaN,1991.0,연립다세대,중개거래,서울 은평구
1,2024,11500,강서구,10300,화곡동,1.0,대지,924.0,4.0,팔팔빌라,...,35000,39.24,27.0000,2.0,NaN,NaN,1986.0,연립다세대,직거래,NaN
2,2024,11560,영등포구,11100,당산동1가,1.0,대지,143.0,0.0,다솔시티하임,...,30000,29.54,14.0000,5.0,NaN,NaN,2017.0,연립다세대,직거래,NaN
3,2024,11560,영등포구,12800,양평동4가,1.0,대지,220.0,0.0,해울빌,...,36000,40.41,63.6400,3.0,NaN,NaN,2021.0,오피스텔,중개거래,서울 용산구
4,2024,11410,서대문구,11200,대현동,1.0,대지,90.0,77.0,유씨유 이대,...,19300,17.31,30.8725,5.0,NaN,NaN,2018.0,오피스텔,중개거래,서울 서대문구

### 문제 2. 데이터의 행, 열 개수를 확인하세요 (`shape`).

In [ ]:
df.shape
# 77523개의 행, 21개의 컬럼

(77523, 21)

### 문제 3. 각 컬럼의 타입과 결측치를 포함한 요약 정보를 확인하세요 (`info()`).

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 77523 entries, 0 to 77522
Data columns (total 21 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   접수연도              77523 non-null  int64
 1   자치구코드             77523 non-null  int64
 2   자치구명              77522 non-null  object
 3   법정동코드             77523 non-null  int64
 4   법정동명              77523 non-null  object
 5   지번구분              74965 non-null  float64
 6   지번구분명             74965 non-null  object
 7   본번                74964 non-null  object
 8   부번                74964 non-null  object
 9   건물명               74964 non-null  object
 10  계약일               77523 non-null  int64
 11  물건금액(만원)          77523 non-null  int64
 12  건물면적(㎡)           77523 non-null  float64
 13  토지면적(㎡)           72446 non-null  float64
 14  층                 74965 non-null  float64
 15  권리구분              700 non-null    object
 16  취소일               3172 non-null   float64
 17  건축년도              77256 non-null  float64
 18  건물용도              77523 non-null  object
 19  신고구분              77521 non-null  object
 20  신고한 개업공인중개사 시군구명  68669 non-null  object
dtypes: float64(6), int64(5), object(10)
memory usage: 12.4+ MB

### 문제 4. 수치형 컬럼들의 통계 요약을 확인하세요 (`describe()`).

In [ ]:
df.describe().round(1)
# 수가 이상하게 나와서 round로 정리

,접수연도,자치구코드,법정동코드,지번구분,계약일,물건금액(만원),건물면적(㎡),토지면적(㎡),층,취소일,건축년도
count,77523.0,77523.0,77523.0,74965.0,77523.0,77523.0,77523.0,72446.0,74965.0,3172.0,77256.0
mean,2024.0,11456.4,10948.6,1.0,20240336.4,88598.7,68.0,18.7,7.9,20240615.6,1986.8
std,0.0,186.1,1228.4,0.1,1446.5,87196.0,53.1,122.4,6.3,241.2,190.4
min,2024.0,11110.0,10100.0,1.0,20210208.0,2600.0,8.5,0.0,-2.0,20240102.0,0.0
25%,2024.0,11305.0,10200.0,1.0,20240327.0,32000.0,41.8,0.0,3.0,20240423.0,1996.0
50%,2024.0,11470.0,10600.0,1.0,20240605.0,66000.0,59.9,0.0,6.0,20240624.0,2004.0
75%,2024.0,11620.0,11000.0,1.0,20240724.0,115000.0,84.9,27.0,11.0,20240817.0,2016.0
max,2024.0,26230.0,18700.0,3.0,20241014.0,2850000.0,2932.3,30822.0,68.0,20241014.0,2024.0

### 문제 5. `['자치구명','법정동명','계약일','물건금액(만원)','건물면적(㎡)']` 열만 선택해 처음 5행을 출력하세요.

In [11]:
df[['자치구명','법정동명','계약일','물건금액(만원)','건물면적(㎡)']].head()

   자치구명   법정동명       계약일  물건금액(만원)  건물면적(㎡)
0   은평구    녹번동  20241014     16400    53.07
1   강서구    화곡동  20241014     35000    39.24
2  영등포구  당산동1가  20241014     30000    29.54
3  영등포구  양평동4가  20241014     36000    40.41
4  서대문구    대현동  20241014     19300    17.31

### 문제 6. `계약일`을 날짜형으로 변환한 뒤, `info()`로 타입 변화를 확인하세요 (사용 방법 : `pd.to_datetime` -> `pd.to_datetime(df['컬럼명']`)).

In [13]:
df['계약일'] = pd.to_datetime(df['계약일'])
df['계약일'].info()

<class 'pandas.core.series.Series'>
RangeIndex: 77523 entries, 0 to 77522
Series name: 계약일
Non-Null Count  Dtype
--------------  -----
77523 non-null  datetime64[ns]
dtypes: datetime64[ns](1)
memory usage: 605.8 KB

### 문제 7. `.loc`으로 0~9행(끝 포함)과 문제 5의 5개 열을 선택해 보세요.

In [14]:
df.loc[0:9, ['자치구명','법정동명','계약일','물건금액(만원)','건물면적(㎡)']]

   자치구명   법정동명                           계약일  물건금액(만원)  건물면적(㎡)
0   은평구    녹번동 1970-01-01 00:00:00.020241014     16400    53.07
1   강서구    화곡동 1970-01-01 00:00:00.020241014     35000    39.24
2  영등포구  당산동1가 1970-01-01 00:00:00.020241014     30000    29.54
3  영등포구  양평동4가 1970-01-01 00:00:00.020241014     36000    40.41
4  서대문구    대현동 1970-01-01 00:00:00.020241014     19300    17.31
5   동작구   신대방동 1970-01-01 00:00:00.020241014    744000  1502.31
6   성동구  하왕십리동 1970-01-01 00:00:00.020241014     28850    27.51
7   금천구    시흥동 1970-01-01 00:00:00.020241014      9300    14.22
8  동대문구    장안동 1970-01-01 00:00:00.020241014     76000   107.97
9   강서구   내발산동 1970-01-01 00:00:00.020241014     15900    37.98

### 문제 8. `.iloc`으로 0~10행(끝 제외)과 열 위치 `[0,1,6,7,8]`을 선택해 보세요.

In [15]:
df.iloc[0:11, [0,1,6,7,8]]

    접수연도  자치구코드 지번구분명      본번     부번
0   2024  11380    대지    86.0  125.0
1   2024  11500    대지   924.0    4.0
2   2024  11560    대지   143.0    0.0
3   2024  11560    대지   220.0    0.0
4   2024  11410    대지    90.0   77.0
5   2024  11590   NaN     NaN    NaN
6   2024  11200    대지   890.0  181.0
7   2024  11545    대지   882.0   61.0
8   2024  11230    대지   580.0    0.0
9   2024  11500    대지   688.0    8.0
10  2024  11230    대지  1158.0   50.0

### 문제 9. 불리언 필터로 `자치구명 == '강남구'` AND `건물면적(㎡) >= 85`인 행만 선택하고 `['자치구명','법정동명','건물면적(㎡)','물건금액(만원)']`만 보세요.

In [24]:
mask = (df['자치구명'] == '강남구') & (df['건물면적(㎡)'] >= 85)
seoul2024_gangnam_85 = df.loc[mask, ['자치구명','법정동명','건물면적(㎡)','물건금액(만원)']]

### 문제 10. `건축년도 >= 2000`인 행만 선택하고 `['자치구명','건축년도','건물용도']`를 보세요.

In [25]:
mask = df['건축년도'] >= 2000
df.loc[mask, ['자치구명','건축년도','건물용도']]

       자치구명    건축년도   건물용도
2      영등포구  2017.0  연립다세대
3      영등포구  2021.0   오피스텔
4      서대문구  2018.0   오피스텔
6       성동구  2017.0   오피스텔
7       금천구  2012.0    아파트
...     ...     ...    ...
77511   도봉구  2001.0    아파트
77512   강북구  2023.0  연립다세대
77514   양천구  2004.0    아파트
77515   서초구  2009.0    아파트
77516   광진구  2018.0  연립다세대

[51629 rows x 3 columns]

### 문제 11. `건물용도`의 분포를 확인하세요 (`value_counts()`), 상위 5개만 확인(`head()`).

In [26]:
df['건물용도'].value_counts()

건물용도
아파트      46027
연립다세대    21184
오피스텔      7754
단독다가구     2558
Name: count, dtype: int64

### 문제 12. 컬럼별 결측치 개수를 확인하세요 (`isnull().sum()`).

In [27]:
df.isnull().sum()

접수연도                    0
자치구코드                   0
자치구명                    1
법정동코드                   0
법정동명                    0
지번구분                 2558
지번구분명                2558
본번                   2559
부번                   2559
건물명                  2559
계약일                     0
물건금액(만원)                0
건물면적(㎡)                 0
토지면적(㎡)              5077
층                    2558
권리구분                76823
취소일                 74351
건축년도                  267
건물용도                    0
신고구분                    2
신고한 개업공인중개사 시군구명     8854
dtype: int64

### 문제 13. 문제 9의 필터 결과를 `seoul2024_gangnam_85.csv`로 저장하세요 (`to_csv`).

In [30]:
seoul2024_gangnam_85.to_csv('seoul2024_gangnam_85.csv', index = False)
#seoul2024_gangnam_85.csv