In [1]:
print("hello world")

hello world

In [2]:
pip install pandas

Requirement already satisfied: pandas in c:\python_course\.venv\lib\site-packages (2.3.3)
Requirement already satisfied: numpy>=1.26.0 in c:\python_course\.venv\lib\site-packages (from pandas) (2.4.1)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\python_course\.venv\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\python_course\.venv\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in c:\python_course\.venv\lib\site-packages (from pandas) (2025.3)
Requirement already satisfied: six>=1.5 in c:\python_course\.venv\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 25.3 -> 26.0
[notice] To update, run: python.exe -m pip install --upgrade pip

In [24]:
import pandas as pd

df = pd.read_csv("train.csv")
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object
 11  Embarked     889 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB

In [32]:
df.iloc[4]
df.iloc[1, 8]

'PC 17599'

In [30]:
df.loc[2]

PassengerId                         3
Survived                            1
Pclass                              3
Name           Heikkinen, Miss. Laina
Sex                            female
Age                              26.0
SibSp                               0
Parch                               0
Ticket               STON/O2. 3101282
Fare                            7.925
Cabin                             NaN
Embarked                            S
Name: 2, dtype: object

In [35]:
df.loc[1:3, ['Survived', 'Name', 'Sex','Age']]

   Survived                                               Name     Sex   Age
1         1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0
2         1                             Heikkinen, Miss. Laina  female  26.0
3         1       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0

In [13]:
s = pd.Series(["윤서", "규리","영탁"], index=['a','b','c'], name='basic')

In [14]:
s.index

Index(['a', 'b', 'c'], dtype='object')

In [15]:
s.values

array(['윤서', '규리', '영탁'], dtype=object)

In [16]:
s1 = pd.Series([100, 200], index=['A','B'])
s2 = pd.Series([1, 2],     index=['B','C'])

print(s1 + s2)

A      NaN
B    201.0
C      NaN
dtype: float64

In [19]:
df = pd.DataFrame({'name' : ['lee', 'seo'], 'age' : [20, 22]})

In [20]:
df.shape

(2, 2)

In [22]:
df.head()

  name  age
0  lee   20
1  seo   22

In [23]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2 entries, 0 to 1
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   name    2 non-null      object
 1   age     2 non-null      int64
dtypes: int64(1), object(1)
memory usage: 164.0+ bytes

In [ ]:
df.to_csv('preprocessed_train.csv', index=False) # 인덱스는 저장하지 마라!

In [37]:
df = pd.DataFrame({ "name": ["천준석", "어제연", "이현지", "문길래"], "grade": ["F", "S", "SS", "SSS" ], "power": ["very weak", "strong", "strong", "very strong"]}, index=[10,20,30,40])
df

   name grade        power
10  천준석     F    very weak
20  어제연     S       strong
30  이현지    SS       strong
40  문길래   SSS  very strong

In [ ]:
# 1 20, 30의 이름과 힘을 기입할 것임
# 2 어제연의 그레이드와 힘
# 3 천, 어, 이의 그래이드 출력